### ISSUE TITLE
QuickContacts crashes

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-samples#10]
QuickContacts app crashes on iOS 64-bit 8.0 device when clicking on Edit Unknown Contact
```
9/24/14 1:55:04 PM: [ERROR] AppLauncher failed with an exception:
9/24/14 1:55:04 PM: [ERROR] java.lang.RuntimeException: Unexpected response from debugserver: $X00;description:5465726d696e617465642064756520746f207369676e616c2036;#00
9/24/14 1:55:04 PM: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:737)
9/24/14 1:55:04 PM: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:667)
9/24/14 1:55:04 PM: [ERROR] 	at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:928)
9/24/14 1:55:04 PM: [ERROR] 	at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)
```

Same on 32-bit iOS 7.1

```
2014-09-24 13:57:37.650 QuickContacts[334:60b] -[__NSCFType length]: unrecognized selector sent to instance 0x17659c10
2014-09-24 13:57:37.655 QuickContacts[334:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType length]: unrecognized selector sent to instance 0x17659c10'
*** First throw call stack:
(0x2e774f83 0x3925bccf 0x2e778917 0x2e777203 0x2e6c6768 0x2e74d685 0x2e6cf083 0x2dda5c5b 0x2dda4ee9 0x2ddd0617 0x2dda4b1d 0x2ddaa389 0x3106747b 0x310655eb 0x31065421 0x3106834d 0x31067f25 0x2ddc8401 0x310d77ab 0x2ddaa20f 0x30fac6df 0x2e6be1fd 0x2e6b7be5 0x30fac865 0x3112243f 0x3103fd63 0x3103fb6d 0x3103fb05 0x30f91d59 0x30c0f62b 0x30c0ae3b 0x30c0accd 0x30c0a6df 0x30c0a4ef 0x30c0421d 0x2e740255 0x2e73dbf9 0x2e73df3b 0x2e6a8ebf 0x2e6a8ca3 0x335a3663 0x30ff514d 0x4c95a5 0x4c8b3b 0x4c8b7b 0x6714f3 0x687543 0x68049f 0x68211b 0x682175 0x67c58b 0x675053 0x17c000)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by saruno** [comment]
Hi robovm,

When i run QuickContacts app, i got an error

java.lang.NullPointerException

at java.io.File.fixSlashes(File.java)

at java.io.File.(File.java)

at com.bgate.testradio.QuickContactsViewController.accessGrantedForAddressBook(QuickContactsViewController.java)

at com.bgate.testradio.QuickContactsViewController.checkAddressBookAccess(QuickContactsViewController.java)

at com.bgate.testradio.QuickContactsViewController.(QuickContactsViewController.java)

at com.bgate.testradio.QuickContacts.didFinishLaunching(QuickContacts.java)

at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Unknown Source)

at org.robovm.apple.uikit.UIApplication.main(Native Method)

at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)

at com.bgate.testradio.QuickContacts.main(QuickContacts.java)

It's error when run this method

@SuppressWarnings("unchecked")
private void accessGrantedForAddressBook () {
// Load data from the plist file

    String plist = NSBundle.getMainBundle().findResourcePath("Menu", "plist");
    menuArray = (NSArray<NSDictionary<NSString, NSString>>)NSArray.read(new File(plist));
    getTableView().reloadData();
}
Please help me to fix this !

**Comment by badlogic** [comment]
This only happens with Menu.plist can not be read. If your file hierarchy and your robovm.xml look like this, there shouldn't be an issue:

![http://sht.tl/lgsEnc](http://sht.tl/lgsEnc)
