### ISSUE TITLE
QuickContact Example Crash

### ISSUE THREAD

**Issue by saruno** [robovm/robovm-samples#32]
Hi robovm,

When i run QuickContacts app, i got an error 

java.lang.NullPointerException

at java.io.File.fixSlashes(File.java)

at java.io.File.<init>(File.java)

at com.bgate.testradio.QuickContactsViewController.accessGrantedForAddressBook(QuickContactsViewController.java)

at com.bgate.testradio.QuickContactsViewController.checkAddressBookAccess(QuickContactsViewController.java)

at com.bgate.testradio.QuickContactsViewController.<init>(QuickContactsViewController.java)

at com.bgate.testradio.QuickContacts.didFinishLaunching(QuickContacts.java)

at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Unknown Source)

at org.robovm.apple.uikit.UIApplication.main(Native Method)

at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)

at com.bgate.testradio.QuickContacts.main(QuickContacts.java)

It's error when run this method 

@SuppressWarnings("unchecked")
    private void accessGrantedForAddressBook () {
        // Load data from the plist file

        String plist = NSBundle.getMainBundle().findResourcePath("Menu", "plist");
        menuArray = (NSArray<NSDictionary<NSString, NSString>>)NSArray.read(new File(plist));
        getTableView().reloadData();
    }

Please help me to fix this !

**Comment by badlogic** [comment]
I just ran the sample from Eclipse without a problem. Did you modify the project in any way? The `robovm.xml` file must list the `resources/` folder as  a resource folder, and the Menu.plist file must be contained in the `resources/` folder, like here: 

![http://sht.tl/lgsEnc](http://sht.tl/lgsEnc)
